<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/pandas/datacleaning_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/e_commerce_orders_dataset.csv',encoding='latin1')
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,david WILLIAMS,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,Cancelled
1,ORD-1705,SARAH WILLIAMS,sarah.williams@yahoo.com,560-949-3793,01-Jun-2023,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,david Jones,david.jones@gmail.com,(866) 859-6633,10/11/2023,Electronics,7,426.43,2985.01,processing
3,ORD-1553,chris Miller,chris.miller@hotmail.com,NaN,01/01/2024,Toys,7,431.19,3018.33,Completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,06/04/2023,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023/07/20 00:00:00,Electronics,10,322.60,3226.00,Cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,10-Feb-2023,CLOTHING,3,9.83,NaN,Completed
1227,ORD-2131,Robert DOe,robert.doe@invalid-domain,4252604426,07/02/2023,electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023/12/23 00:00:00,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023/07/21 00:00:00,Toys,2,408.19,816.38,Completed

To check the columns

In [ ]:
df.columns

Index(['order_id', 'customer_name', 'email', 'phone', 'order_date', 'category',
       'quantity', 'unit_price', 'total_amount', 'status'],
      dtype='object')

Step 1: Checking the column names

STEP 2 — Check duplicate values

In [ ]:
df[df.duplicated]
int(df.duplicated().sum())

30

step3:Remove or Drop the duplicate values

In [ ]:
df.drop_duplicates(inplace=True)
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,david WILLIAMS,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,Cancelled
1,ORD-1705,SARAH WILLIAMS,sarah.williams@yahoo.com,560-949-3793,01-Jun-2023,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,david Jones,david.jones@gmail.com,(866) 859-6633,10/11/2023,Electronics,7,426.43,2985.01,processing
3,ORD-1553,chris Miller,chris.miller@hotmail.com,NaN,01/01/2024,Toys,7,431.19,3018.33,Completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,06/04/2023,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023/07/20 00:00:00,Electronics,10,322.60,3226.00,Cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,10-Feb-2023,CLOTHING,3,9.83,NaN,Completed
1227,ORD-2131,Robert DOe,robert.doe@invalid-domain,4252604426,07/02/2023,electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023/12/23 00:00:00,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023/07/21 00:00:00,Toys,2,408.19,816.38,Completed

In [ ]:
df[df.duplicated()]
int(df.duplicated().sum())

0

STEP 4 — Clean unwanted spaces and capitalization

In [ ]:
df['customer_name'] = df['customer_name'].str.strip().str.title()

In [ ]:
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,David Williams,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,Cancelled
1,ORD-1705,Sarah Williams,sarah.williams@yahoo.com,560-949-3793,01-Jun-2023,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,David Jones,david.jones@gmail.com,(866) 859-6633,10/11/2023,Electronics,7,426.43,2985.01,processing
3,ORD-1553,Chris Miller,chris.miller@hotmail.com,NaN,01/01/2024,Toys,7,431.19,3018.33,Completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,06/04/2023,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023/07/20 00:00:00,Electronics,10,322.60,3226.00,Cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,10-Feb-2023,CLOTHING,3,9.83,NaN,Completed
1227,ORD-2131,Robert Doe,robert.doe@invalid-domain,4252604426,07/02/2023,electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023/12/23 00:00:00,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023/07/21 00:00:00,Toys,2,408.19,816.38,Completed

Step 5: Cleaning category values

In [ ]:
df['category'] = df['category'].str.strip().str.title()
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,David Williams,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,Cancelled
1,ORD-1705,Sarah Williams,sarah.williams@yahoo.com,560-949-3793,01-Jun-2023,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,David Jones,david.jones@gmail.com,(866) 859-6633,10/11/2023,Electronics,7,426.43,2985.01,processing
3,ORD-1553,Chris Miller,chris.miller@hotmail.com,NaN,01/01/2024,Toys,7,431.19,3018.33,Completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,06/04/2023,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023/07/20 00:00:00,Electronics,10,322.60,3226.00,Cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,10-Feb-2023,Clothing,3,9.83,NaN,Completed
1227,ORD-2131,Robert Doe,robert.doe@invalid-domain,4252604426,07/02/2023,Electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023/12/23 00:00:00,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023/07/21 00:00:00,Toys,2,408.19,816.38,Completed

Step 6 — Clean status

In [ ]:
df['status'] = df['status'].str.strip().str.lower()
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,David Williams,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,cancelled
1,ORD-1705,Sarah Williams,sarah.williams@yahoo.com,560-949-3793,01-Jun-2023,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,David Jones,david.jones@gmail.com,(866) 859-6633,10/11/2023,Electronics,7,426.43,2985.01,processing
3,ORD-1553,Chris Miller,chris.miller@hotmail.com,NaN,01/01/2024,Toys,7,431.19,3018.33,completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,06/04/2023,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023/07/20 00:00:00,Electronics,10,322.60,3226.00,cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,10-Feb-2023,Clothing,3,9.83,NaN,completed
1227,ORD-2131,Robert Doe,robert.doe@invalid-domain,4252604426,07/02/2023,Electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023/12/23 00:00:00,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023/07/21 00:00:00,Toys,2,408.19,816.38,completed

Step 6: Changing the datatype of order_date

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1229
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1200 non-null   object
 1   customer_name  1200 non-null   object
 2   email          1151 non-null   object
 3   phone          730 non-null    object
 4   order_date     1163 non-null   object
 5   category       1200 non-null   object
 6   quantity       1200 non-null   int64
 7   unit_price     1200 non-null   float64
 8   total_amount   1100 non-null   float64
 9   status         1200 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 103.1+ KB

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'],format='mixed')
df

,order_id,customer_name,email,phone,order_date,category,quantity,unit_price,total_amount,status
0,ORD-1549,David Williams,david.williams@outlook.com,136-574-8999,2023-04-20,Toys,5,431.84,2159.20,cancelled
1,ORD-1705,Sarah Williams,sarah.williams@yahoo.com,560-949-3793,2023-06-01,Home & Kitchen,6,160.57,963.42,processing
2,ORD-1245,David Jones,david.jones@gmail.com,(866) 859-6633,2023-10-11,Electronics,7,426.43,2985.01,processing
3,ORD-1553,Chris Miller,chris.miller@hotmail.com,NaN,2024-01-01,Toys,7,431.19,3018.33,completed
4,ORD-2165,Jane Miller,jane.miller@gmail.com,NaN,2023-06-04,Electronics,9,376.53,3388.77,processing
...,...,...,...,...,...,...,...,...,...,...
1225,ORD-2045,Robert Davis,robert.davis@hotmail.com,909-190-7938,2023-07-20,Electronics,10,322.60,3226.00,cancelled
1226,ORD-2096,Emily Miller,emily.miller@outlook.com,441-884-6317,2023-02-10,Clothing,3,9.83,NaN,completed
1227,ORD-2131,Robert Doe,robert.doe@invalid-domain,4252604426,2023-07-02,Electronics,9,412.73,3714.57,pending
1228,ORD-1861,Jane Davis,jane.davis@outlook.com,400-974-3666,2023-12-23,Electronics,2,223.79,447.58,pending
1229,ORD-2127,Emily Wilson,emily.wilson@outlook.com,2814515678,2023-07-21,Toys,2,408.19,816.38,completed

Step 8 — Check NA values

In [ ]:
df.isna().sum()

order_id           0
customer_name      0
email             49
phone            470
order_date        37
category           0
quantity           0
unit_price         0
total_amount     100
status             0
dtype: int64

Step 9 — Fill missing email and phone

In [ ]:
df['email'] = df['email'].fillna('Not Available')
df['phone'] = df['phone'].fillna('Not Available')
df['order_date'] = df['order_date'].fillna(0)

In [ ]:
df.isna().sum()

order_id           0
customer_name      0
email              0
phone              0
order_date         0
category           0
quantity           0
unit_price         0
total_amount     100
status             0
dtype: int64

Step 10 — Fill missing total amount

In [ ]:
df['total_amount'] = df['total_amount'].fillna(
    df['quantity'] * df['unit_price']
)

Step 11 — Final check

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 0 to 1229
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1200 non-null   object
 1   customer_name  1200 non-null   object
 2   email          1200 non-null   object
 3   phone          1200 non-null   object
 4   order_date     1200 non-null   object
 5   category       1200 non-null   object
 6   quantity       1200 non-null   int64
 7   unit_price     1200 non-null   float64
 8   total_amount   1200 non-null   float64
 9   status         1200 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 103.1+ KB

In [ ]:
df.isna().sum()

order_id         0
customer_name    0
email            0
phone            0
order_date       0
category         0
quantity         0
unit_price       0
total_amount     0
status           0
dtype: int64