<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA EXPLORATION

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("/content/flipkart_sales.csv",encoding = "latin1")
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [35]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1

In [36]:
df.head(15)

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
5,ORD00006,Mixer Grinder,Home & Kitchen,10475.03,2,20950.06,2024-10-22,Wallet,1.7
6,ORD00007,Sneakers,Clothing,38647.72,3,115943.16,2024-07-04,Wallet,2.0
7,ORD00008,Table Lamp,Home & Kitchen,24818.59,3,74455.77,2024-12-27,Debit Card,2.4
8,ORD00009,Jacket,Clothing,1987.39,2,3974.78,2025-01-18,Debit Card,2.6
9,ORD00010,Tablet,Electronics,26876.51,2,53753.02,2024-03-14,Debit Card,4.0
10,ORD00011,Perfume,Beauty,46409.57,5,232047.85,2025-02-08,UPI,2.3
11,ORD00012,Lipstick,Beauty,48780.78,5,243903.90,2024-04-13,UPI,1.3
12,ORD00013,Educational Book,Books,6670.82,5,33354.10,2024-02-23,COD,1.2
13,ORD00014,Smartphone,Electronics,10826.05,1,10826.05,2024-06-02,Wallet,3.7
14,ORD00015,Comic Book,Books,6839.10,1,6839.10,2024-09-12,Credit Card,1.6

In [37]:
df.tail()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [38]:
df.tail(15)

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
985,ORD00986,Bedsheet,Home & Kitchen,17253.67,3,51761.01,2024-11-24,Debit Card,4.6
986,ORD00987,Educational Book,Books,27920.20,5,139601.00,2024-02-14,Wallet,2.7
987,ORD00988,Jacket,Clothing,46055.88,5,230279.40,2024-12-06,COD,4.2
988,ORD00989,Smartwatch,Electronics,49569.30,4,198277.20,2024-05-11,COD,1.2
989,ORD00990,Educational Book,Books,35948.16,5,179740.80,2024-10-30,Wallet,2.5
990,ORD00991,Fiction Novel,Books,9189.91,5,45949.55,2024-07-28,Wallet,4.9
991,ORD00992,Mixer Grinder,Home & Kitchen,6075.65,2,12151.30,2024-03-06,Credit Card,2.1
992,ORD00993,Mixer Grinder,Home & Kitchen,25511.46,2,51022.92,2024-11-27,Net Banking,3.7
993,ORD00994,Mixer Grinder,Home & Kitchen,5815.52,4,23262.08,2024-10-12,UPI,2.2
994,ORD00995,Sneakers,Clothing,11479.89,3,34439.67,2024-07-30,Net Banking,2.5
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   object
 1   Product Name       1000 non-null   object
 2   Category           1000 non-null   object
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   object
 7   Payment Method     1000 non-null   object
 8   Customer Rating    1000 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 70.4+ KB

In [40]:
df.describe()

        Price (INR)  Quantity Sold  Total Sales (INR)  Customer Rating
count   1000.000000    1000.000000        1000.000000      1000.000000
mean   24520.258260       3.097000       75213.112740         3.011100
std    14187.611227       1.410525       59457.598352         1.145408
min      139.850000       1.000000         419.550000         1.000000
25%    12378.905000       2.000000       28581.765000         2.000000
50%    24650.015000       3.000000       57358.300000         3.100000
75%    35981.925000       4.000000      110618.595000         4.000000
max    49911.750000       5.000000      243903.900000         5.000000

In [41]:
df.describe(include=object)

        Order ID      Product Name     Category  Order Date Payment Method
count       1000              1000         1000        1000           1000
unique      1000                25            5         346              6
top     ORD01000  Educational Book  Electronics  2024-11-28            UPI
freq           1                64          217          10            176

In [42]:
df.columns

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating'],
      dtype='object')

In [43]:
df["Product Name"].unique()

array(['Educational Book', 'Jeans', 'Face Cream', 'Smartwatch',
       'Cookware Set', 'Mixer Grinder', 'Sneakers', 'Table Lamp',
       'Jacket', 'Tablet', 'Perfume', 'Lipstick', 'Smartphone',
       'Comic Book', 'Cookbook', 'T-Shirt', 'Bedsheet', 'Hair Dryer',
       'Laptop', 'Shampoo', 'Headphones', 'Fiction Novel',
       'Self-Help Book', 'Sofa Cover', 'Dress'], dtype=object)

In [44]:
df["Category"].unique()

array(['Books', 'Clothing', 'Beauty', 'Electronics', 'Home & Kitchen'],
      dtype=object)

In [45]:
df["Category"].value_counts()

Category
Electronics       217
Books             209
Home & Kitchen    193
Beauty            192
Clothing          189
Name: count, dtype: int64

In [46]:
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [47]:
df.sort_values(by="Quantity Sold")

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
14,ORD00015,Comic Book,Books,6839.10,1,6839.10,2024-09-12,Credit Card,1.6
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
13,ORD00014,Smartphone,Electronics,10826.05,1,10826.05,2024-06-02,Wallet,3.7
957,ORD00958,Fiction Novel,Books,10435.03,1,10435.03,2024-09-23,Debit Card,3.1
962,ORD00963,Lipstick,Beauty,47055.28,1,47055.28,2024-06-16,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...
371,ORD00372,Smartphone,Electronics,704.55,5,3522.75,2024-05-28,Debit Card,4.0
10,ORD00011,Perfume,Beauty,46409.57,5,232047.85,2025-02-08,UPI,2.3
11,ORD00012,Lipstick,Beauty,48780.78,5,243903.90,2024-04-13,UPI,1.3
12,ORD00013,Educational Book,Books,6670.82,5,33354.10,2024-02-23,COD,1.2
15,ORD00016,Mixer Grinder,Home & Kitchen,18197.89,5,90989.45,2024-03-30,Debit Card,1.6

In [48]:
df.sort_values(by="Quantity Sold", ascending=False)

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
968,ORD00969,Laptop,Electronics,36615.73,5,183078.65,2024-04-10,Net Banking,2.0
10,ORD00011,Perfume,Beauty,46409.57,5,232047.85,2025-02-08,UPI,2.3
31,ORD00032,Hair Dryer,Beauty,15046.01,5,75230.05,2024-10-17,COD,1.1
984,ORD00985,Jeans,Clothing,40905.69,5,204528.45,2025-01-27,COD,1.9
982,ORD00983,Comic Book,Books,5412.90,5,27064.50,2024-06-30,COD,2.1
...,...,...,...,...,...,...,...,...,...
366,ORD00367,Educational Book,Books,35304.99,1,35304.99,2024-08-06,COD,2.0
681,ORD00682,Bedsheet,Home & Kitchen,17539.19,1,17539.19,2024-07-07,Wallet,3.9
369,ORD00370,Educational Book,Books,20353.40,1,20353.40,2024-07-07,UPI,2.9
674,ORD00675,Laptop,Electronics,40753.52,1,40753.52,2024-03-01,Debit Card,4.2
819,ORD00820,Cookware Set,Home & Kitchen,35777.51,1,35777.51,2024-12-23,Net Banking,3.2

In [49]:
df["Product Name"].isnull().sum()

np.int64(0)

In [52]:
df = pd.read_csv("/content/blinkit_data.csv",)

In [53]:
df

,Unnamed: 0,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,Low Fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,8519,Low Fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,8520,Low Fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,8521,Regular,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,8522,Regular,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [54]:
df.head()

,Unnamed: 0,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0