<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({
    'order_id' : [1,2,3],
    'order_name' : ['bag','pen','laptop'],
    'order_price' : [1000,20,30000]
})
df1

   order_id order_name  order_price
0         1        bag         1000
1         2        pen           20
2         3     laptop        30000

In [ ]:
df2 = pd.DataFrame({
    'order_id' : [4,5,6],
    'order_name' : ['blanket','pillow','matress'],
    'order_price' : [100,200,15000]
})
df2

   order_id order_name  order_price
0         4    blanket          100
1         5     pillow          200
2         6    matress        15000

In [ ]:
data = {'discount': [5000,1000,2000,25000]}
data

{'discount': [5000, 1000, 2000, 25000]}

concate : it is used to concatenate the 2 or more data frames

Syntax:
for rows:
var = pd.concat([dataframe1,dataframe2,...],ignore_index = True)

fro columns:
var = pd.concat([dataframe1,dataframe2,dataframe3,...],axis = 1)

In [ ]:
df3 = pd.concat([df1,df2], ignore_index=True)
df3

   order_id order_name  order_price
0         1        bag         1000
1         2        pen           20
2         3     laptop        30000
3         4    blanket          100
4         5     pillow          200
5         6    matress        15000

In [ ]:
data1 = {
  'customer_id': ['CUST501','CUST782','CUST501','CUST990'],
  'customer_name': ['john','BOB','Max','Anu'],
  'city': ['Banglore','Hyderabad','Banglore','Chennai'],
  'quantity' : [1,2,3,1],
  'product_id' : ['P101','P102','P103','P105']
}
order = pd.DataFrame(data1)
order

  customer_id customer_name       city  quantity product_id
0     CUST501          john   Banglore         1       P101
1     CUST782           BOB  Hyderabad         2       P102
2     CUST501           Max   Banglore         3       P103
3     CUST990           Anu    Chennai         1       P105

In [ ]:
data = {
    'product_id' : ['P101','P102','P103','P104'],
    'product_name' : ['Laptop','Mouse','Keyboard','Pen drive'],
    'Price': [50000, 500, 1500,500]
}
product = pd.DataFrame(data)
print(product)

  product_id product_name  Price
0       P101       Laptop  50000
1       P102        Mouse    500
2       P103     Keyboard   1500
3       P104    Pen drive    500

1.CROSS JOIN

In [ ]:
pd.merge(order,product,how='cross')

,customer_id,customer_name,city,quantity,product_id_x,product_id_y,product_name,Price
0,CUST501,john,Banglore,1,P101,P101,Laptop,50000
1,CUST501,john,Banglore,1,P101,P102,Mouse,500
2,CUST501,john,Banglore,1,P101,P103,Keyboard,1500
3,CUST501,john,Banglore,1,P101,P104,Pen drive,500
4,CUST782,BOB,Hyderabad,2,P102,P101,Laptop,50000
5,CUST782,BOB,Hyderabad,2,P102,P102,Mouse,500
6,CUST782,BOB,Hyderabad,2,P102,P103,Keyboard,1500
7,CUST782,BOB,Hyderabad,2,P102,P104,Pen drive,500
8,CUST501,Max,Banglore,3,P103,P101,Laptop,50000
9,CUST501,Max,Banglore,3,P103,P102,Mouse,500
10,CUST501,Max,Banglore,3,P103,P103,Keyboard,1500
11,CUST501,Max,Banglore,3,P103,P104,Pen drive,500
12,CUST990,Anu,Chennai,1,P105,P101,Laptop,50000
13,CUST990,Anu,Chennai,1,P105,P102,Mouse,500
14,CUST990,Anu,Chennai,1,P105,P103,Keyboard,1500
15,CUST990,Anu,Chennai,1,P105,P104,Pen drive,500

2.INNER JOIN

In [ ]:
pd.merge(order,product,on='product_id',how='inner')

,customer_id,customer_name,city,quantity,product_id,product_name,Price
0,CUST501,john,Banglore,1,P101,Laptop,50000
1,CUST782,BOB,Hyderabad,2,P102,Mouse,500
2,CUST501,Max,Banglore,3,P103,Keyboard,1500

3.OUTER JOIN

In [ ]:
pd.merge(order,product,on='product_id',how='outer')

,customer_id,customer_name,city,quantity,product_id,product_name,Price
0,CUST501,john,Banglore,1.0,P101,Laptop,50000.0
1,CUST782,BOB,Hyderabad,2.0,P102,Mouse,500.0
2,CUST501,Max,Banglore,3.0,P103,Keyboard,1500.0
3,NaN,NaN,NaN,NaN,P104,Pen drive,500.0
4,CUST990,Anu,Chennai,1.0,P105,NaN,NaN

4.LEFT OUTER

In [ ]:
pd.merge(order,product,on='product_id',how='left')

,customer_id,customer_name,city,quantity,product_id,product_name,Price
0,CUST501,john,Banglore,1,P101,Laptop,50000.0
1,CUST782,BOB,Hyderabad,2,P102,Mouse,500.0
2,CUST501,Max,Banglore,3,P103,Keyboard,1500.0
3,CUST990,Anu,Chennai,1,P105,NaN,NaN

5.RIGHT OUTER JOIN

In [ ]:
pd.merge(order,product,on='product_id',how='right')

,customer_id,customer_name,city,quantity,product_id,product_name,Price
0,CUST501,john,Banglore,1.0,P101,Laptop,50000
1,CUST782,BOB,Hyderabad,2.0,P102,Mouse,500
2,CUST501,Max,Banglore,3.0,P103,Keyboard,1500
3,NaN,NaN,NaN,NaN,P104,Pen drive,500

In [ ]:
pd