<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#Series in pandas
sal = pd.Series([1000,1500,2000,2500,3000])
sal

0    1000
1    1500
2    2000
3    2500
4    3000
dtype: int64

In [3]:
# Name attribute in Series
age = pd.Series([20,25,30,35,40],name = 'age')
age

0    20
1    25
2    30
3    35
4    40
Name: age, dtype: int64

In [4]:
#Index in Series
age = pd.Series([20,21,22,23,24,25],index = ['sai','vamsi','sam','tarak','bob','bhAAi'],name="age")
age

sai      20
vamsi    21
sam      22
tarak    23
bob      24
bhAAi    25
Name: age, dtype: int64

In [5]:
#Operations on Series
movies = pd.Series(['paradise','endcore','varanasi','raaka','dragon'],name="movies")
movies

0    paradise
1     endcore
2    varanasi
3       raaka
4      dragon
Name: movies, dtype: object

In [6]:
#1)Indexing on Series
print(movies[0])
print(movies[4])
print(movies[3])

paradise
dragon
raaka

In [7]:
movies = pd.Series(['paradise','endcore','varanasi','raaka','dragon'],index=['nani','RDJ','BOB','AA','NTR'],name="movies")
movies

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
NTR       dragon
Name: movies, dtype: object

In [8]:
#indexing on series based on label
print(movies['nani'])
print(movies['NTR'])

paradise
dragon

In [9]:
#slicing on Series -> Indexing
print(movies[0:4])

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
Name: movies, dtype: object

In [10]:
print(movies[0:5])

nani    paradise
RDJ      endcore
BOB     varanasi
AA         raaka
NTR       dragon
Name: movies, dtype: object

In [11]:
print(movies[::2])

nani    paradise
BOB     varanasi
NTR       dragon
Name: movies, dtype: object

In [12]:
print(movies[1::2])

RDJ    endcore
AA       raaka
Name: movies, dtype: object

In [13]:
#slicing on series based on label
movies = pd.Series(['paradise','endcore','raaka','kaaka','salaar',"varanasi"],index=['nani','RDJ','AA','chiru','darling','bob'],name="movies")
movies

nani       paradise
RDJ         endcore
AA            raaka
chiru         kaaka
darling      salaar
bob        varanasi
Name: movies, dtype: object

In [14]:
print(movies['nani':'darling'])

nani       paradise
RDJ         endcore
AA            raaka
chiru         kaaka
darling      salaar
Name: movies, dtype: object

In [15]:
print(movies[:'AA'])

nani    paradise
RDJ      endcore
AA         raaka
Name: movies, dtype: object

In [16]:

#filtering on series:
#syntax: var[condition]
sal = pd.Series([15000,35000,20000,45000,50000,25000],name="salary")
sal

0    15000
1    35000
2    20000
3    45000
4    50000
5    25000
Name: salary, dtype: int64

In [17]:
print(sal[sal>30000])

1    35000
3    45000
4    50000
Name: salary, dtype: int64

In [18]:
print(sal[sal<30000])

0    15000
2    20000
5    25000
Name: salary, dtype: int64

In [19]:
print(sal[sal==50000])

4    50000
Name: salary, dtype: int64

In [20]:
print(sal[(sal>30000)&(sal<50000)])

1    35000
3    45000
Name: salary, dtype: int64

In [21]:
print(sal[(sal>50000)|(sal<35000)])

0    15000
2    20000
5    25000
Name: salary, dtype: int64

In [22]:
# not sal>30000
print(sal[sal<30000])

0    15000
2    20000
5    25000
Name: salary, dtype: int64

In [23]:
print(sal[~(sal>30000)])

0    15000
2    20000
5    25000
Name: salary, dtype: int64

#Pandas DataFrames

In [24]:
d={
    "sid":["S101","S102","S103","S104","S105"],
    "sname":["Mahi","Sai","Seeta","Vishnu","Ram"],
    "branch":["CSE","CSE","IT","ECE","Civil"],
    "loc":["vjwd","vzg","hyd","bnglr","ayodhya"]
}
df=pd.DataFrame(d)
df

    sid   sname branch      loc
0  S101    Mahi    CSE     vjwd
1  S102     Sai    CSE      vzg
2  S103   Seeta     IT      hyd
3  S104  Vishnu    ECE    bnglr
4  S105     Ram  Civil  ayodhya

In [25]:
#indexing
df["sname"]

0      Mahi
1       Sai
2     Seeta
3    Vishnu
4       Ram
Name: sname, dtype: object

In [26]:
df["branch"]

0      CSE
1      CSE
2       IT
3      ECE
4    Civil
Name: branch, dtype: object

In [27]:
df[["sname","branch"]]

    sname branch
0    Mahi    CSE
1     Sai    CSE
2   Seeta     IT
3  Vishnu    ECE
4     Ram  Civil

In [28]:
df["sname"][2]

'Seeta'

In [29]:
df["loc"][4]

'ayodhya'

In [30]:
#slicing:
df[1:4]

    sid   sname branch    loc
1  S102     Sai    CSE    vzg
2  S103   Seeta     IT    hyd
3  S104  Vishnu    ECE  bnglr

In [31]:
df[3:]

    sid   sname branch      loc
3  S104  Vishnu    ECE    bnglr
4  S105     Ram  Civil  ayodhya

In [32]:
df[:2]

    sid sname branch   loc
0  S101  Mahi    CSE  vjwd
1  S102   Sai    CSE   vzg

In [33]:
df[0::2]

    sid  sname branch      loc
0  S101   Mahi    CSE     vjwd
2  S103  Seeta     IT      hyd
4  S105    Ram  Civil  ayodhya

In [34]:
df[-1:]

    sid sname branch      loc
4  S105   Ram  Civil  ayodhya

In [35]:
df[2:4]

    sid   sname branch    loc
2  S103   Seeta     IT    hyd
3  S104  Vishnu    ECE  bnglr

In [36]:
df.loc[1:4,["sname","branch"]]
df.loc[2:,["sname","loc"]]
df.loc[1::2,["sid","sname"]]
df.loc[1:3,["branch"]]

  branch
1    CSE
2     IT
3    ECE

In [37]:
df

    sid   sname branch      loc
0  S101    Mahi    CSE     vjwd
1  S102     Sai    CSE      vzg
2  S103   Seeta     IT      hyd
3  S104  Vishnu    ECE    bnglr
4  S105     Ram  Civil  ayodhya

In [38]:
df.iloc[1:4,1:3]
df.iloc[2:,0:3]
df.iloc[1:3,1:3]
df.iloc[0:3,:1]

    sid
0  S101
1  S102
2  S103

In [39]:
nutrition={
    "items":["eggs","oats","sunflower seeds","dry fruits",
             "chicken","fish"],
    "clrs":[18,35,165,220,200,280],
    "prtn":[6,14,32,15,24,18],
    "fat":[3,2,7,15,10,12],
    "price":[7,250,120,700,250,140]

}
df=pd.DataFrame(nutrition)
df

             items  clrs  prtn  fat  price
0             eggs    18     6    3      7
1             oats    35    14    2    250
2  sunflower seeds   165    32    7    120
3       dry fruits   220    15   15    700
4          chicken   200    24   10    250
5             fish   280    18   12    140

In [40]:
#filtering:
df[df["clrs"]<165]
df[df["prtn"]==18]
df[df["price"]>250]
df[(df["clrs"]<100)&(df["fat"]<10)]
df[(df["price"]>250)&(df["prtn"]>=15)]
df[(df["prtn"]<18)|(df["fat"]>15)]

        items  clrs  prtn  fat  price
0        eggs    18     6    3      7
1        oats    35    14    2    250
3  dry fruits   220    15   15    700