<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/PandasDataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Cleaning

In [3]:
import pandas as pd

importing the data set

In [4]:
df = pd.read_csv('/content/amazon_fires.csv',encoding = "latin1")
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

Step1:Renaming the column names:

In [5]:
d = {
    'ano':'year',
    'estado':'state',
    'mes':'month',
    'numero':'number_of_fires',
    'encontro':'date'
}
df.rename(columns=d,inplace=True)
df

      year     month      state number_of_fires      date
0     1998   Janeiro       Acre         0 Fires  1/1/1998
1     1999   Janeiro       Acre         0 Fires  1/1/1999
2     2000   Janeiro       Acre         0 Fires  1/1/2000
3     2001   Janeiro       Acre         0 Fires  1/1/2001
4     2002   Janeiro       Acre         0 Fires  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  Dezembro  Tocantins             128  1/1/2012
6450  2013  Dezembro  Tocantins              85  1/1/2013
6451  2014  Dezembro  Tocantins             223  1/1/2014
6452  2015  Dezembro  Tocantins             373  1/1/2015
6453  2016  Dezembro  Tocantins             119  1/1/2016

[6454 rows x 5 columns]

To check the duplicate values

In [6]:
df[df.duplicated()]
int(df.duplicated().sum())

30

STEP2: droppingor removing the duplicate values

In [7]:
df.drop_duplicates(inplace=True)
df

      year     month      state number_of_fires      date
0     1998   Janeiro       Acre         0 Fires  1/1/1998
1     1999   Janeiro       Acre         0 Fires  1/1/1999
2     2000   Janeiro       Acre         0 Fires  1/1/2000
3     2001   Janeiro       Acre         0 Fires  1/1/2001
4     2002   Janeiro       Acre         0 Fires  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  Dezembro  Tocantins             128  1/1/2012
6450  2013  Dezembro  Tocantins              85  1/1/2013
6451  2014  Dezembro  Tocantins             223  1/1/2014
6452  2015  Dezembro  Tocantins             373  1/1/2015
6453  2016  Dezembro  Tocantins             119  1/1/2016

[6424 rows x 5 columns]

In [8]:
df[df.duplicated()]
int(df.duplicated().sum())

0

Step3: removing the unwanted data from the column values

In [9]:
df['number_of_fires']=df['number_of_fires'].str.strip(' Fires')
df

      year     month      state number_of_fires      date
0     1998   Janeiro       Acre               0  1/1/1998
1     1999   Janeiro       Acre               0  1/1/1999
2     2000   Janeiro       Acre               0  1/1/2000
3     2001   Janeiro       Acre               0  1/1/2001
4     2002   Janeiro       Acre               0  1/1/2002
...    ...       ...        ...             ...       ...
6449  2012  Dezembro  Tocantins             128  1/1/2012
6450  2013  Dezembro  Tocantins              85  1/1/2013
6451  2014  Dezembro  Tocantins             223  1/1/2014
6452  2015  Dezembro  Tocantins             373  1/1/2015
6453  2016  Dezembro  Tocantins             119  1/1/2016

[6424 rows x 5 columns]

Step4: changing the datatype of the column

In [10]:
df['number_of_fires']=df['number_of_fires'].astype(float)
df.info()
#df

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             6424 non-null   int64
 1   month            6424 non-null   object
 2   state            6424 non-null   object
 3   number_of_fires  6292 non-null   float64
 4   date             6424 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 559.2+ KB

STEP5: Changing the data in the columns

In [11]:
d = {
    'Janeiro':'January',
    'Fevereiro':'February',
    'Março':'March',
    'Abril':'April',
    'Maio':'May',
    'Junho':'June',
    'Julho':'July',
    'Agosto':'August',
    'Setembro':'September',
    'Outubro':'October',
    'Novembro':'November',
    'Dezembro':'December'
}
df['month']=df['month'].map(d)
df

      year     month      state  number_of_fires      date
0     1998   January       Acre              0.0  1/1/1998
1     1999   January       Acre              0.0  1/1/1999
2     2000   January       Acre              0.0  1/1/2000
3     2001   January       Acre              0.0  1/1/2001
4     2002   January       Acre              0.0  1/1/2002
...    ...       ...        ...              ...       ...
6449  2012  December  Tocantins            128.0  1/1/2012
6450  2013  December  Tocantins             85.0  1/1/2013
6451  2014  December  Tocantins            223.0  1/1/2014
6452  2015  December  Tocantins            373.0  1/1/2015
6453  2016  December  Tocantins            119.0  1/1/2016

[6424 rows x 5 columns]

step6: checking the na(not available values):

In [12]:
df.isna().any()
df.isna().sum()

year                 0
month                0
state                0
number_of_fires    132
date                 0
dtype: int64

step7: Fillig NA values

In [13]:
df['number_of_fires']= df['number_of_fires'].fillna(0)
df

      year     month      state  number_of_fires      date
0     1998   January       Acre              0.0  1/1/1998
1     1999   January       Acre              0.0  1/1/1999
2     2000   January       Acre              0.0  1/1/2000
3     2001   January       Acre              0.0  1/1/2001
4     2002   January       Acre              0.0  1/1/2002
...    ...       ...        ...              ...       ...
6449  2012  December  Tocantins            128.0  1/1/2012
6450  2013  December  Tocantins             85.0  1/1/2013
6451  2014  December  Tocantins            223.0  1/1/2014
6452  2015  December  Tocantins            373.0  1/1/2015
6453  2016  December  Tocantins            119.0  1/1/2016

[6424 rows x 5 columns]

In [14]:
int(df['number_of_fires'].isna().sum())

0

In [15]:
df

      year     month      state  number_of_fires      date
0     1998   January       Acre              0.0  1/1/1998
1     1999   January       Acre              0.0  1/1/1999
2     2000   January       Acre              0.0  1/1/2000
3     2001   January       Acre              0.0  1/1/2001
4     2002   January       Acre              0.0  1/1/2002
...    ...       ...        ...              ...       ...
6449  2012  December  Tocantins            128.0  1/1/2012
6450  2013  December  Tocantins             85.0  1/1/2013
6451  2014  December  Tocantins            223.0  1/1/2014
6452  2015  December  Tocantins            373.0  1/1/2015
6453  2016  December  Tocantins            119.0  1/1/2016

[6424 rows x 5 columns]

step8: Rearranging the column order[link text](https://)

In [16]:
new_order = [4,1,0,2,3]
df = df[df.columns[new_order]]
df

          date     month  year      state  number_of_fires
0     1/1/1998   January  1998       Acre              0.0
1     1/1/1999   January  1999       Acre              0.0
2     1/1/2000   January  2000       Acre              0.0
3     1/1/2001   January  2001       Acre              0.0
4     1/1/2002   January  2002       Acre              0.0
...        ...       ...   ...        ...              ...
6449  1/1/2012  December  2012  Tocantins            128.0
6450  1/1/2013  December  2013  Tocantins             85.0
6451  1/1/2014  December  2014  Tocantins            223.0
6452  1/1/2015  December  2015  Tocantins            373.0
6453  1/1/2016  December  2016  Tocantins            119.0

[6424 rows x 5 columns]

STEP9: drop unwanted columns

In [17]:
#df=df.drop(['year','month'],axis=1)
#df

Step10: replacing the val in a column

In [18]:
df['month']= df['month'].str.replace('January','Jan')
df

          date     month  year      state  number_of_fires
0     1/1/1998       Jan  1998       Acre              0.0
1     1/1/1999       Jan  1999       Acre              0.0
2     1/1/2000       Jan  2000       Acre              0.0
3     1/1/2001       Jan  2001       Acre              0.0
4     1/1/2002       Jan  2002       Acre              0.0
...        ...       ...   ...        ...              ...
6449  1/1/2012  December  2012  Tocantins            128.0
6450  1/1/2013  December  2013  Tocantins             85.0
6451  1/1/2014  December  2014  Tocantins            223.0
6452  1/1/2015  December  2015  Tocantins            373.0
6453  1/1/2016  December  2016  Tocantins            119.0

[6424 rows x 5 columns]

**Ex2**

In [19]:
df= pd.DataFrame({
    'Name': ['A','B','C','D'],
    'City': ['Hyderabad','Bangalore','Mumbai','Chennai']
})
df

  Name       City
0    A  Hyderabad
1    B  Bangalore
2    C     Mumbai
3    D    Chennai

In [20]:
df['City'].map({
    'Hyderabad':'HYD',
    'Bangalore':'BLR',
})

0    HYD
1    BLR
2    NaN
3    NaN
Name: City, dtype: object