<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/pandasFinalTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use Pandas functions and methods to solve each question.

Create new DataFrames wherever instructed.

For merge and concat questions, display the resulting DataFrame.

For pivot questions, use pd.pivot_table().

For feature engineering questions, add the required columns to the DataFrame.

For data cleaning questions, verify the changes using suitable Pandas methods.

In [ ]:
import pandas as pd

In [ ]:

data = {
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 109],
    "order_date": [ "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-08",
        "2026-01-09", "2026-02-02", "2026-02-05", "2026-02-08",
        "2026-02-10", "2026-02-10"],
    "customer": ["Rahul", "Priya", "Amit", "Sneha", "Rahul",
        "Priya", "Kiran", "Amit", "Sneha", "Sneha"],
    "city": ["Hyderabad", "Chennai", "Hyderabad", "Bangalore",
        "Hyderabad", "Chennai", "Missing", "hyderabad",
        "Bangalore", "Bangalore" ],
    "product": ["Laptop", "Mobile", "Headphones", "Laptop", "Mobile",
        "Laptop", "Headphones", "Mobile", "Headphones", "Headphones"],
    "quantity": [1, 2, 3, 1, 2, 1, 2, 1, 2, 2],
    "price": [50000, 15000, 2000, 50000, 15000, 50000, 2000, 15000, 2000, 2000],
    "payment_mode": ["UPI", "Card", "UPI", "Cash", "UPI",
        "Card", "UPI", "Card", "Cash", "Cash" ]}
df = pd.DataFrame(data)
print(df)

   order_id  order_date customer       city     product  quantity  price  \
0       101  2026-01-05    Rahul  Hyderabad      Laptop         1  50000
1       102  2026-01-06    Priya    Chennai      Mobile         2  15000
2       103  2026-01-07     Amit  Hyderabad  Headphones         3   2000
3       104  2026-01-08    Sneha  Bangalore      Laptop         1  50000
4       105  2026-01-09    Rahul  Hyderabad      Mobile         2  15000
5       106  2026-02-02    Priya    Chennai      Laptop         1  50000
6       107  2026-02-05    Kiran    Missing  Headphones         2   2000
7       108  2026-02-08     Amit  hyderabad      Mobile         1  15000
8       109  2026-02-10    Sneha  Bangalore  Headphones         2   2000
9       109  2026-02-10    Sneha  Bangalore  Headphones         2   2000

  payment_mode
0          UPI
1         Card
2          UPI
3         Cash
4          UPI
5         Card
6          UPI
7         Card
8         Cash
9         Cash

1Q)Display the first 5 rows and the last 3 rows of the DataFrame.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     int64
 1   order_date    10 non-null     object
 2   customer      10 non-null     object
 3   city          10 non-null     object
 4   product       10 non-null     object
 5   quantity      10 non-null     int64
 6   price         10 non-null     int64
 7   payment_mode  10 non-null     object
dtypes: int64(3), object(5)
memory usage: 772.0+ bytes

2Q0Display the number of rows and columns in the DataFrame.

In [ ]:
df.shape

(10, 8)

3Q)Display all column names and their respective data types.

In [ ]:
df.columns
df.dtypes

order_id         int64
order_date      object
customer        object
city            object
product         object
quantity         int64
price            int64
payment_mode    object
dtype: object

4Q)Check whether the DataFrame contains any missing values and display the count of missing values in each column.

In [ ]:
df.isnull().sum()

order_id        0
order_date      0
customer        0
city            0
product         0
quantity        0
price           0
payment_mode    0
dtype: int64

5Q)Find the number of unique customers, cities, products, and payment modes.

In [ ]:
df['customer'].nunique()
df['city'].nunique()
df['product'].nunique()
df['payment_mode'].nunique()

3

6Q)Display the statistical summary of all numerical columns. Also, identify the minimum and maximum price.

In [ ]:
df.describe()

         order_id   quantity         price
count   10.000000  10.000000     10.000000
mean   105.400000   1.700000  20300.000000
std      2.875181   0.674949  21265.778456
min    101.000000   1.000000   2000.000000
25%    103.250000   1.000000   2000.000000
50%    105.500000   2.000000  15000.000000
75%    107.750000   2.000000  41250.000000
max    109.000000   3.000000  50000.000000

In [ ]:
df['price'].min()

2000

In [ ]:
df['price'].max()

50000

7Q)Find all duplicate rows in the DataFrame and display them.

In [ ]:
df[df.duplicated()]

,order_id,order_date,customer,city,product,quantity,price,payment_mode
9,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash

8Q)Remove duplicate rows from the DataFrame.

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, customer, city, product, quantity, price, payment_mode]
Index: []

9Q)Replace the text "Missing" in the city column with an appropriate missing value.

In [ ]:
df["city"] = df["city"].replace("Missing", "Hyderabad")
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,hyderabad,Mobile,1,15000,Card
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash

10Q)Standardize the values in the city column so that "Hyderabad" and "hyderabad" are treated as the same city.

In [ ]:
df['city'] = df['city'].str.capitalize()
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash

11Q)Convert the order_date column into a proper datetime data type.

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df.dtypes

order_id                 int64
order_date      datetime64[ns]
customer                object
city                    object
product                 object
quantity                 int64
price                    int64
payment_mode            object
dtype: object

12Q)After cleaning the data, verify that duplicate rows have been removed and display the updated DataFrame.

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [ ]:
df.isnull().sum()

order_id        0
order_date      0
customer        0
city            0
product         0
quantity        0
price           0
payment_mode    0
dtype: int64

In [ ]:
df.dtypes

order_id                 int64
order_date      datetime64[ns]
customer                object
city                    object
product                 object
quantity                 int64
price                    int64
payment_mode            object
dtype: object

In [ ]:
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash

1Q)Create a DataFrame named df_january containing only January 2026 orders and another DataFrame named df_february containing only February 2026 orders. Concatenate them vertically into a single DataFrame.

In [ ]:
df_january = df[df['order_date'].dt.month == 1]
df_february = df[df['order_date'].dt.month == 2]
df_combined = pd.concat([df_january, df_february],axis=0)
df_combined

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash

2Q)Create two DataFrames: one containing the first 5 orders and another containing the remaining orders. Concatenate them vertically and verify the resulting row count.

In [ ]:
df_first_5 = df.iloc[:5]
df_remaining = df.iloc[5:]
df_combined = pd.concat([df_first_5, df_remaining],axis=0)
df_combined

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash




3Q)Create two DataFrames from df: one containing order_id, customer, and city, and another containing order_id, product, and price. Concatenate them horizontally.

In [ ]:
df_order_customer_city = df[['order_id', 'customer', 'city']]
df_order_product_price = df[['order_id', 'product', 'price']]

4Q)Create two DataFrames containing orders from Hyderabad and Chennai, respectively. Concatenate them vertically and display the combined DataFrame.

In [ ]:
df_hyderabad = df[df['city'] == 'Hyderabad']
df_chennai = df[df['city'] == 'Chennai']
df_combined = pd.concat([df_hyderabad, df_chennai],axis=0)
df_combined

,order_id,order_date,customer,city,product,quantity,price,payment_mode
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card

In [73]:
customer_info = pd.DataFrame({
    "customer": ["Rahul", "Priya", "Amit", "Sneha", "Kiran"],
    "age": [25, 28, 30, 24, 32],
    "membership": ["Gold", "Silver", "Gold", "Bronze", "Silver"]})

product_info = pd.DataFrame({
    "product": ["Laptop", "Mobile", "Headphones"],
    "category": ["Electronics", "Electronics", "Accessories"],
    "brand": ["Dell", "Samsung", "Boat"]})

Merge df with customer_info to display each customer's age and membership alongside their order details.

In [74]:
df_merged = pd.merge(df, customer_info, on='customer')
df_merged

,order_id,order_date,customer,city,product,quantity,price,payment_mode,age,membership
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,25,Gold
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,28,Silver
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,30,Gold
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,24,Bronze
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,25,Gold
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,28,Silver
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,32,Silver
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,30,Gold
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,24,Bronze


Merge df with product_info to display the category and brand of every ordered product.

In [75]:
df.merge(product_info, on='product')

,order_id,order_date,customer,city,product,quantity,price,payment_mode,category,brand
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,Electronics,Dell
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,Electronics,Samsung
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,Accessories,Boat
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,Electronics,Dell
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,Electronics,Samsung
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,Electronics,Dell
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,Accessories,Boat
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,Electronics,Samsung
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,Accessories,Boat


Perform a left merge between df and customer_info. Check whether all orders are retained in the result.

In [76]:
df.merge(customer_info, on='customer', how='left')

,order_id,order_date,customer,city,product,quantity,price,payment_mode,age,membership
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,25,Gold
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,28,Silver
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,30,Gold
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,24,Bronze
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,25,Gold
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,28,Silver
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,32,Silver
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,30,Gold
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,24,Bronze


Perform an inner merge between df and customer_info. Compare the number of rows with the original DataFrame.

In [77]:
df.merge(customer_info, on='customer', how='inner')

,order_id,order_date,customer,city,product,quantity,price,payment_mode,age,membership
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,25,Gold
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,28,Silver
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,30,Gold
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,24,Bronze
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,25,Gold
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,28,Silver
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,32,Silver
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,30,Gold
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,24,Bronze


Merge df with product_info and display only the orders where the product category is "Electronics".

In [78]:
df.merge(product_info, on='product', how='left')[df.merge(product_info, on='product', how='left')['category'] == 'Electronics']

,order_id,order_date,customer,city,product,quantity,price,payment_mode,category,brand
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,Electronics,Dell
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,Electronics,Samsung
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,Electronics,Dell
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,Electronics,Samsung
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,Electronics,Dell
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,Electronics,Samsung

Create a pivot table showing the total quantity sold for each product in each city.

In [79]:
df.pivot_table(index='city', columns='product', values='quantity', aggfunc='sum')

product    Headphones  Laptop  Mobile
city
Bangalore         2.0     1.0     NaN
Chennai           NaN     1.0     2.0
Hyderabad         5.0     1.0     3.0



Create a pivot table showing the number of orders for each payment mode across different cities.

In [80]:
df.pivot_table(index='city', columns='payment_mode', values='order_id', aggfunc='count')

payment_mode  Card  Cash  UPI
city
Bangalore      NaN   2.0  NaN
Chennai        2.0   NaN  NaN
Hyderabad      1.0   NaN  4.0



Create a pivot table displaying the total quantity sold for each product, with cities as columns.

In [81]:
df.pivot_table(index='city', columns='product', values='quantity', aggfunc='sum')

product    Headphones  Laptop  Mobile
city
Bangalore         2.0     1.0     NaN
Chennai           NaN     1.0     2.0
Hyderabad         5.0     1.0     3.0



Create a pivot table showing the average price of each product for every payment mode.

In [82]:
df.pivot_table(index='payment_mode', columns='product', values='price', aggfunc='mean')

product       Headphones   Laptop   Mobile
payment_mode
Card                 NaN  50000.0  15000.0
Cash              2000.0  50000.0      NaN
UPI               2000.0  50000.0  15000.0



Create a pivot table displaying the total quantity sold and average price for each product.

In [83]:
df.pivot_table(index='product', values=['quantity', 'price'], aggfunc={'quantity': 'sum', 'price': 'mean'})

              price  quantity
product
Headphones   2000.0         7
Laptop      50000.0         3
Mobile      15000.0         5

Create a new column named total_amount by multiplying quantity by price for every order.

In [88]:
df['total_amount'] = df['quantity'] * df['price']
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode,total_amount
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,50000
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,30000
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,6000
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,50000
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,30000
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,50000
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,4000
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,15000
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,4000

Extract the year, month number, month name, and day name from order_date into separate columns.

In [89]:
df['year'] = df['order_date'].dt.year
df['month_number'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode,total_amount,year,month_number,month_name
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,50000,2026,1,January
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,30000,2026,1,January
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,6000,2026,1,January
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,50000,2026,1,January
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,30000,2026,1,January
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,50000,2026,2,February
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,4000,2026,2,February
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,15000,2026,2,February
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,4000,2026,2,February

 Create a new column named price_category based on the following conditions:

Price greater than ₹20,000: "Expensive"
Price between ₹5,000 and ₹20,000 inclusive: "Medium"
Price below ₹5,000: "Budget"

In [91]:
df.loc[df['price'] > 20000, 'price_category'] = 'Expensive'
df.loc[(df['price'] >= 5000) & (df['price'] <= 20000), 'price_category'] = 'Medium'
df.loc[df['price'] < 5000, 'price_category'] = 'Budget'
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode,total_amount,year,month_number,month_name,price_category
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,50000,2026,1,January,Expensive
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,30000,2026,1,January,Medium
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,6000,2026,1,January,Budget
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,50000,2026,1,January,Expensive
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,30000,2026,1,January,Medium
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,50000,2026,2,February,Expensive
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,4000,2026,2,February,Budget
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,15000,2026,2,February,Medium
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,4000,2026,2,February,Budget


Create a new column named order_size based on the quantity ordered:

Quantity = 1: "Single"
Quantity = 2: "Small"
Quantity greater than 2: "Bulk"

In [92]:
df.loc[df['quantity'] == 1, 'order_size'] = 'Single'
df.loc[df['quantity'] == 2, 'order_size'] = 'Small'
df.loc[df['quantity'] > 2, 'order_size'] = 'Bulk'
df

,order_id,order_date,customer,city,product,quantity,price,payment_mode,total_amount,year,month_number,month_name,price_category,order_size
0,101,2026-01-05,Rahul,Hyderabad,Laptop,1,50000,UPI,50000,2026,1,January,Expensive,Single
1,102,2026-01-06,Priya,Chennai,Mobile,2,15000,Card,30000,2026,1,January,Medium,Small
2,103,2026-01-07,Amit,Hyderabad,Headphones,3,2000,UPI,6000,2026,1,January,Budget,Bulk
3,104,2026-01-08,Sneha,Bangalore,Laptop,1,50000,Cash,50000,2026,1,January,Expensive,Single
4,105,2026-01-09,Rahul,Hyderabad,Mobile,2,15000,UPI,30000,2026,1,January,Medium,Small
5,106,2026-02-02,Priya,Chennai,Laptop,1,50000,Card,50000,2026,2,February,Expensive,Single
6,107,2026-02-05,Kiran,Hyderabad,Headphones,2,2000,UPI,4000,2026,2,February,Budget,Small
7,108,2026-02-08,Amit,Hyderabad,Mobile,1,15000,Card,15000,2026,2,February,Medium,Single
8,109,2026-02-10,Sneha,Bangalore,Headphones,2,2000,Cash,4000,2026,2,February,Budget,Small