<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/Pandas/pandas_test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1Q) Create a data frame named df to store employee information for a company.
The data frame should contain the following columns

In [63]:
import pandas as pd

In [64]:
d = {
    "Name": ["Vamsi", "Sai Kumari", "Kiran", "Sneha", "Sathwik",
             "Purna", "Anjali", "Rohit", "Meena", "Suresh",
             "Divya", "Naveen", "Pooja", "Akash", "Swathi",
             "Harsha", "Neha", "Vikram", "Keerthi", "Manoj"],

    "Age": [24, 27, 31, 25, 29,
            26, 32, 28, 23, 35,
            30, 27, 24, 33, 26,
            29, 31, 25, 28, 34],

    "Department": ["IT", "HR", "Finance", "IT", "Sales",
                   "IT", "HR", "Finance", "Sales", "IT",
                   "Finance", "Sales", "HR", "IT", "Finance",
                   "Sales", "IT", "HR", "Finance", "Sales"],

    "Salary": [45000, 52000, 68000, 48000, 55000,
               62000, 58000, 72000, 42000, 85000,
               70000, 60000, 50000, 78000, 65000,
               57000, 90000, 53000, 74000, 61000],

    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai",
             "Hyderabad", "Chennai", "Bangalore", "Pune", "Hyderabad",
             "Mumbai", "Pune", "Hyderabad", "Bangalore", "Chennai",
             "Pune", "Hyderabad", "Chennai", "Bangalore", "Mumbai"],

    "Experience": [1, 3, 6, 2, 4,
                   5, 7, 8, 1, 10,
                   6, 4, 2, 9, 5,
                   3, 8, 2, 7, 5]
}

df = pd.DataFrame(d)

In [65]:
#Q1) the hr team wants to understand the structure of the employee DAta Frame before performing any analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     object
 1   Age         20 non-null     int64
 2   Department  20 non-null     object
 3   Salary      20 non-null     int64
 4   City        20 non-null     object
 5   Experience  20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB

In [66]:
#Q2) you have to find out all the column names available in the emplotee DataFrame
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'City', 'Experience'], dtype='object')

In [67]:
#Q3)the data frame contanis a thousands of employee rocords . you have to quickly inspect the first 5 employee records
df.head()

         Name  Age Department  Salary       City  Experience
0       Vamsi   24         IT   45000  Hyderabad           1
1  Sai Kumari   27         HR   52000    Chennai           3
2       Kiran   31    Finance   68000  Bangalore           6
3       Sneha   25         IT   48000  Hyderabad           2
4     Sathwik   29      Sales   55000     Mumbai           4

In [68]:
#4Q)The hr team wants to inspect the last 5 records of the employee records
df.tail()

       Name  Age Department  Salary       City  Experience
15   Harsha   29      Sales   57000       Pune           3
16     Neha   31         IT   90000  Hyderabad           8
17   Vikram   25         HR   53000    Chennai           2
18  Keerthi   28    Finance   74000  Bangalore           7
19    Manoj   34      Sales   61000     Mumbai           5

In [69]:
#Q5.The HR manager wants a statistical summary of the Age, Salary, and Experience columns.
df[['Age', 'Salary', 'Experience']].describe()

             Age        Salary  Experience
count  20.000000     20.000000   20.000000
mean   28.350000  62250.000000    4.900000
std     3.498496  13029.824089    2.693071
min    23.000000  42000.000000    1.000000
25%    25.750000  52750.000000    2.750000
50%    28.000000  60500.000000    5.000000
75%    31.000000  70500.000000    7.000000
max    35.000000  90000.000000   10.000000

In [70]:
#Q6. Find all the different departments present in the company.
df['Department'].unique()

array(['IT', 'HR', 'Finance', 'Sales'], dtype=object)

In [71]:
#Q7. The company wants to know how many employees belong to each department
df['Department'].value_counts()

Department
IT         6
Finance    5
Sales      5
HR         4
Name: count, dtype: int64

In [72]:
#Q8. Find the number of employees from each city and display the cities from highest number of employees to lowest.
df['City'].value_counts().sort_values()

City
Mumbai       3
Pune         3
Bangalore    4
Chennai      4
Hyderabad    6
Name: count, dtype: int64

In [73]:
df['City'].value_counts() #highest to lowest number of employee

City
Hyderabad    6
Chennai      4
Bangalore    4
Mumbai       3
Pune         3
Name: count, dtype: int64

In [74]:
#Q9. Sort the employee DataFrame based on Salary from lowest to highest.
df.sort_values('Salary')

          Name  Age Department  Salary       City  Experience
8        Meena   23      Sales   42000       Pune           1
0        Vamsi   24         IT   45000  Hyderabad           1
3        Sneha   25         IT   48000  Hyderabad           2
12       Pooja   24         HR   50000  Hyderabad           2
1   Sai Kumari   27         HR   52000    Chennai           3
17      Vikram   25         HR   53000    Chennai           2
4      Sathwik   29      Sales   55000     Mumbai           4
15      Harsha   29      Sales   57000       Pune           3
6       Anjali   32         HR   58000    Chennai           7
11      Naveen   27      Sales   60000       Pune           4
19       Manoj   34      Sales   61000     Mumbai           5
5        Purna   26         IT   62000  Hyderabad           5
14      Swathi   26    Finance   65000    Chennai           5
2        Kiran   31    Finance   68000  Bangalore           6
10       Divya   30    Finance   70000     Mumbai           6
7        Rohit   28    Finance   72000  Bangalore           8
18     Keerthi   28    Finance   74000  Bangalore           7
13       Akash   33         IT   78000  Bangalore           9
9       Suresh   35         IT   85000  Hyderabad          10
16        Neha   31         IT   90000  Hyderabad           8

In [75]:
#Q10. The management wants to see the employees with the highest salary first.
df.sort_values('Salary', ascending=False)

          Name  Age Department  Salary       City  Experience
16        Neha   31         IT   90000  Hyderabad           8
9       Suresh   35         IT   85000  Hyderabad          10
13       Akash   33         IT   78000  Bangalore           9
18     Keerthi   28    Finance   74000  Bangalore           7
7        Rohit   28    Finance   72000  Bangalore           8
10       Divya   30    Finance   70000     Mumbai           6
2        Kiran   31    Finance   68000  Bangalore           6
14      Swathi   26    Finance   65000    Chennai           5
5        Purna   26         IT   62000  Hyderabad           5
19       Manoj   34      Sales   61000     Mumbai           5
11      Naveen   27      Sales   60000       Pune           4
6       Anjali   32         HR   58000    Chennai           7
15      Harsha   29      Sales   57000       Pune           3
4      Sathwik   29      Sales   55000     Mumbai           4
17      Vikram   25         HR   53000    Chennai           2
1   Sai Kumari   27         HR   52000    Chennai           3
12       Pooja   24         HR   50000  Hyderabad           2
3        Sneha   25         IT   48000  Hyderabad           2
0        Vamsi   24         IT   45000  Hyderabad           1
8        Meena   23      Sales   42000       Pune           1

In [76]:
#Q11. Check the entire DataFrame and identify which values are missing.
df.isnull()

     Name    Age  Department  Salary   City  Experience
0   False  False       False   False  False       False
1   False  False       False   False  False       False
2   False  False       False   False  False       False
3   False  False       False   False  False       False
4   False  False       False   False  False       False
5   False  False       False   False  False       False
6   False  False       False   False  False       False
7   False  False       False   False  False       False
8   False  False       False   False  False       False
9   False  False       False   False  False       False
10  False  False       False   False  False       False
11  False  False       False   False  False       False
12  False  False       False   False  False       False
13  False  False       False   False  False       False
14  False  False       False   False  False       False
15  False  False       False   False  False       False
16  False  False       False   False  False       False
17  False  False       False   False  False       False
18  False  False       False   False  False       False
19  False  False       False   False  False       False

In [77]:
#Q12. The hr teams dont wants to see the every True and False instead, the HR team wants to know how many missing values are present in each column.
df.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
City          0
Experience    0
dtype: int64

In [78]:
#Q13) using the same cities Series , find how many times each city occurs. Then arrange the result from highest frequency to lowest
cities = pd.Series([
    'Hyderabad',
    'Chennai',
    'Hyderabad',
    'Mumbai',
    'Chennai',
    'Bangalore',
    'Hyderabad',
    'Pune'
])
cities.value_counts()

Hyderabad    3
Chennai      2
Mumbai       1
Bangalore    1
Pune         1
Name: count, dtype: int64

In [79]:
#Q14. Sort the employees using the following priority:
#Department → ascending
#Salary → descending
#Experience → descending
df.sort_values(
    by=['Department', 'Salary', 'Experience'],
    ascending=[True, False, False]
)

          Name  Age Department  Salary       City  Experience
18     Keerthi   28    Finance   74000  Bangalore           7
7        Rohit   28    Finance   72000  Bangalore           8
10       Divya   30    Finance   70000     Mumbai           6
2        Kiran   31    Finance   68000  Bangalore           6
14      Swathi   26    Finance   65000    Chennai           5
6       Anjali   32         HR   58000    Chennai           7
17      Vikram   25         HR   53000    Chennai           2
1   Sai Kumari   27         HR   52000    Chennai           3
12       Pooja   24         HR   50000  Hyderabad           2
16        Neha   31         IT   90000  Hyderabad           8
9       Suresh   35         IT   85000  Hyderabad          10
13       Akash   33         IT   78000  Bangalore           9
5        Purna   26         IT   62000  Hyderabad           5
3        Sneha   25         IT   48000  Hyderabad           2
0        Vamsi   24         IT   45000  Hyderabad           1
19       Manoj   34      Sales   61000     Mumbai           5
11      Naveen   27      Sales   60000       Pune           4
15      Harsha   29      Sales   57000       Pune           3
4      Sathwik   29      Sales   55000     Mumbai           4
8        Meena   23      Sales   42000       Pune           1

In [80]:
#Q15. Find the top 3 most experienced employees, but if two or more employees have the same experience, arrange those employees by Salary from highest to lowest. Display the result with all columns.
df.sort_values(
    by=['Experience', 'Salary'],
    ascending=[False, False]
).head(3)

      Name  Age Department  Salary       City  Experience
9   Suresh   35         IT   85000  Hyderabad          10
13   Akash   33         IT   78000  Bangalore           9
16    Neha   31         IT   90000  Hyderabad           8